- name: Setup foundry VTT and all dependencies
  hosts: foundry-server

  tasks:
  - name: Setup node package source
    shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install node, npm, unzip and nginx
    become: yes
    apt:
      name: 
        - nodejs
        - unzip
        - nginx
      state: latest

  - name: Install pm2 with node
    become: yes
    community.general.npm:
      name: pm2
      global: yes

  - name: Add pm2 to startup
    become: yes
    shell: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

  - name: Create foundry directory
    file:
      path: ~/foundry
      state: directory

  - name: Create foundryuserdata directory
    file:
      path: ~/foundryuserdata
      state: directory

  - name: Create foundryuserdata/Config directory
    file:
      path: ~/foundryuserdata/Config
      state: directory


  - name: Extract foundry
    unarchive:
      src: foundry.zip
      dest: ~/foundry/

  - name: Generate with self signed SSL cert and key
    shell: openssl req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365 -subj "/C=WE/ST=Nowhere/L=Void/O=Dice rollers/OU=Implementation/CN="

  - name: Configure nginx
    become: yes
    copy:
      src: default
      dest: /etc/nginx/sites-available/default
      owner: ubuntu

  - name: Configure foundry VTT
    become: yes
    copy:
      src: options.json
      dest: /home/ubuntu/foundryuserdata/Config/options.json
      owner: ubuntu

  - name: Add foundry to pm2 task list
    shell: pm2 start "node /home/ubuntu/foundry/resources/app/main.js --dataPath=/home/ubuntu/foundryuserdata" --name foundry

  - name: Save pm2 task list
    shell: pm2 save

  - name: Reboot nginx
    become: yes
    service:
        name: nginx
        state: restarted

  - name: Link to foundry
    debug:
      msg: "https://{{ ansible_ssh_host }}/"