- name: Setup foundry VTT and all dependencies
  hosts: foundry-server

  tasks:
  - name: Check for backup data
    delegate_to: localhost
    stat:
      path: files/foundryuserdata.tar.gz
    register: user_data_backup

  - name: Check for certificate chain data
    delegate_to: localhost
    stat:
      path: files/cert.pem
    register: user_data_certificate_chain

  - name: Check for private key data
    delegate_to: localhost
    stat:
      path: files/key.pem
    register: user_data_private_key

  - name: Setup node package source
    shell: curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -

  - name: Update and upgrade apt packages
    become: yes
    apt:
      upgrade: yes
      update_cache: yes

  - name: Install node, npm, unzip and nginx
    become: yes
    apt:
      name: 
        - nodejs
        - unzip
        - nginx
      state: latest

  - name: Install pm2 with node
    become: yes
    community.general.npm:
      name: pm2
      global: yes

  - name: Add pm2 to startup
    become: yes
    shell: env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu

  - name: Create foundry directory
    file:
      path: ~/foundry
      state: directory

  - name: Create foundryuserdata directory
    file:
      path: ~/foundryuserdata
      state: directory
    when: not user_data_backup.stat.exists

  - name: Create foundryuserdata/Config directory
    file:
      path: ~/foundryuserdata/Config
      state: directory
    when: not user_data_backup.stat.exists

  - name: Configure foundry VTT
    become: yes
    copy:
      src: options.json
      dest: /home/ubuntu/foundryuserdata/Config/options.json
      owner: ubuntu
    when: not user_data_backup.stat.exists

  - name: Restore game backup if exists
    become: yes
    unarchive:
      src: foundryuserdata.tar.gz
      dest: /
      owner: ubuntu
    when: user_data_backup.stat.exists

  - name: Extract foundry
    unarchive:
      src: foundry.zip
      dest: ~/foundry/

  - name: Copy certificate data
    become: yes
    copy:
      src: cert.pem
      dest: /home/ubuntu/cert.pem
      owner: ubuntu
    when: user_data_certificate_chain.stat.exists

  - name: Copy private key data
    become: yes
    copy:
      src: key.pem
      dest: /home/ubuntu/key.pem
      owner: ubuntu
    when: user_data_private_key.stat.exists

  - name: Install certbot with snap
    become: yes
    community.general.snap:
      name: certbot
      classic: true
    when:
    - not user_data_certificate_chain.stat.exists
    - not user_data_private_key.stat.exists

  - name: Ensure certbot is able to be run
    become: yes
    file:
      src: /snap/bin/certbot
      dest: /usr/bin/certbot
      state: link
    when:
    - not user_data_certificate_chain.stat.exists
    - not user_data_private_key.stat.exists

  - name: Generate certificate via certbot
    become: yes
    shell: >
      certbot certonly
      -d {{ url }}
      -m {{ email }}
      --agree-tos
      --nginx
      --non-interactive
      --keep-until-expiring
    when:
    - not user_data_certificate_chain.stat.exists
    - not user_data_private_key.stat.exists

  - name: Copy certificate to expected location
    become: yes
    copy:
      remote_src: true
      src: /etc/letsencrypt/live/{{ url }}/fullchain.pem
      dest: /home/ubuntu/cert.pem
    when:
    - not user_data_certificate_chain.stat.exists
    - not user_data_private_key.stat.exists

  - name: Copy private key to expected location
    become: yes
    copy:
      remote_src: true
      src: /etc/letsencrypt/live/{{ url }}/privkey.pem
      dest: /home/ubuntu/key.pem
    when:
    - not user_data_certificate_chain.stat.exists
    - not user_data_private_key.stat.exists

  - name: Configure nginx
    become: yes
    copy:
      src: default
      dest: /etc/nginx/sites-available/default
      owner: ubuntu

  - name: Add foundry to pm2 task list
    shell: pm2 start "node /home/ubuntu/foundry/resources/app/main.js --dataPath=/home/ubuntu/foundryuserdata" --name foundry

  - name: Save pm2 task list
    shell: pm2 save

  - name: Reboot nginx
    become: yes
    service:
        name: nginx
        state: restarted

  - name: Enter license
    uri:
        url: https://{{ ansible_ssh_host }}/license
        method: POST
        validate_certs: no
        body_format: json
        body:
          action: enterKey
          licenseKey: "{{ foundry_license }}"
    when: not user_data_backup.stat.exists

  - name: Accept terms and conditions
    uri:
        url: https://{{ ansible_ssh_host }}/license
        method: POST
        validate_certs: no
        body_format: json
        status_code: 302
        body:
          agree: on
          accept:

  - name: Link to foundry
    debug:
      msg: "https://{{ url }}/"
